/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueBookingRouteImport } from './routes/venue-booking'
import { Route as SalonManagementRouteImport } from './routes/salon-management'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OrdersRequestsRouteImport } from './routes/orders-requests'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MenuManagementRouteImport } from './routes/menu-management'
import { Route as HotelAdminRouteImport } from './routes/hotel-admin'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as ApiSyncReservationsRouteImport } from './routes/api/sync-reservations'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSaveBookingRouteImport } from './routes/api/save-booking'
import { Route as ApiSalonBookingsRouteImport } from './routes/api/salon-bookings'
import { Route as ApiOrdersAndRequestsRouteImport } from './routes/api/orders-and-requests'
import { Route as ApiNewBookingsCountRouteImport } from './routes/api/new-bookings-count'
import { Route as ApiMenuItemsRouteImport } from './routes/api/menu-items'
import { Route as ApiHallBookingsRouteImport } from './routes/api/hall-bookings'
import { Route as ApiBookingsRecentRouteImport } from './routes/api/bookings-recent'
import { Route as ApiBookingsActiveCountRouteImport } from './routes/api/bookings-active-count'
import { Route as ApiPmsShiftCashoutRouteImport } from './routes/api/pms.shift-cashout'
import { Route as ApiPmsRoomStatusRouteImport } from './routes/api/pms.room-status'
import { Route as ApiPmsMigrateRouteImport } from './routes/api/pms.migrate'
import { Route as ApiMessagesThreadRouteImport } from './routes/api/messages.thread'
import { Route as ApiMessagesReplyRouteImport } from './routes/api/messages.reply'
import { Route as ApiMessagesMessageRouteImport } from './routes/api/messages.message'
import { Route as ApiMessagesMarkReadRouteImport } from './routes/api/messages.mark-read'
import { Route as ApiMessagesConversationsRouteImport } from './routes/api/messages.conversations'
import { Route as ApiMessagesConversationRouteImport } from './routes/api/messages.conversation'
import { Route as ApiMenuItemsIdRouteImport } from './routes/api/menu-items.$id'
import { Route as ApiSalonBookingsIdStatusRouteImport } from './routes/api/salon-bookings.$id.status'
import { Route as ApiRoomOrdersIdStatusRouteImport } from './routes/api/room-orders.$id.status'
import { Route as ApiGuestRequestsIdStatusRouteImport } from './routes/api/guest-requests.$id.status'

const VenueBookingRoute = VenueBookingRouteImport.update({
  id: '/venue-booking',
  path: '/venue-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonManagementRoute = SalonManagementRouteImport.update({
  id: '/salon-management',
  path: '/salon-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRequestsRoute = OrdersRequestsRouteImport.update({
  id: '/orders-requests',
  path: '/orders-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuManagementRoute = MenuManagementRouteImport.update({
  id: '/menu-management',
  path: '/menu-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAdminRoute = HotelAdminRouteImport.update({
  id: '/hotel-admin',
  path: '/hotel-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const ApiSyncReservationsRoute = ApiSyncReservationsRouteImport.update({
  id: '/api/sync-reservations',
  path: '/api/sync-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveBookingRoute = ApiSaveBookingRouteImport.update({
  id: '/api/save-booking',
  path: '/api/save-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalonBookingsRoute = ApiSalonBookingsRouteImport.update({
  id: '/api/salon-bookings',
  path: '/api/salon-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersAndRequestsRoute = ApiOrdersAndRequestsRouteImport.update({
  id: '/api/orders-and-requests',
  path: '/api/orders-and-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewBookingsCountRoute = ApiNewBookingsCountRouteImport.update({
  id: '/api/new-bookings-count',
  path: '/api/new-bookings-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuItemsRoute = ApiMenuItemsRouteImport.update({
  id: '/api/menu-items',
  path: '/api/menu-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHallBookingsRoute = ApiHallBookingsRouteImport.update({
  id: '/api/hall-bookings',
  path: '/api/hall-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRecentRoute = ApiBookingsRecentRouteImport.update({
  id: '/api/bookings-recent',
  path: '/api/bookings-recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsActiveCountRoute = ApiBookingsActiveCountRouteImport.update({
  id: '/api/bookings-active-count',
  path: '/api/bookings-active-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmsShiftCashoutRoute = ApiPmsShiftCashoutRouteImport.update({
  id: '/api/pms/shift-cashout',
  path: '/api/pms/shift-cashout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmsRoomStatusRoute = ApiPmsRoomStatusRouteImport.update({
  id: '/api/pms/room-status',
  path: '/api/pms/room-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmsMigrateRoute = ApiPmsMigrateRouteImport.update({
  id: '/api/pms/migrate',
  path: '/api/pms/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesThreadRoute = ApiMessagesThreadRouteImport.update({
  id: '/api/messages/thread',
  path: '/api/messages/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesReplyRoute = ApiMessagesReplyRouteImport.update({
  id: '/api/messages/reply',
  path: '/api/messages/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesMessageRoute = ApiMessagesMessageRouteImport.update({
  id: '/api/messages/message',
  path: '/api/messages/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesMarkReadRoute = ApiMessagesMarkReadRouteImport.update({
  id: '/api/messages/mark-read',
  path: '/api/messages/mark-read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesConversationsRoute =
  ApiMessagesConversationsRouteImport.update({
    id: '/api/messages/conversations',
    path: '/api/messages/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesConversationRoute = ApiMessagesConversationRouteImport.update({
  id: '/api/messages/conversation',
  path: '/api/messages/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuItemsIdRoute = ApiMenuItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMenuItemsRoute,
} as any)
const ApiSalonBookingsIdStatusRoute =
  ApiSalonBookingsIdStatusRouteImport.update({
    id: '/$id/status',
    path: '/$id/status',
    getParentRoute: () => ApiSalonBookingsRoute,
  } as any)
const ApiRoomOrdersIdStatusRoute = ApiRoomOrdersIdStatusRouteImport.update({
  id: '/api/room-orders/$id/status',
  path: '/api/room-orders/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestRequestsIdStatusRoute =
  ApiGuestRequestsIdStatusRouteImport.update({
    id: '/api/guest-requests/$id/status',
    path: '/api/guest-requests/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-admin': typeof HotelAdminRoute
  '/menu-management': typeof MenuManagementRoute
  '/my-bookings': typeof MyBookingsRoute
  '/offers': typeof OffersRoute
  '/orders-requests': typeof OrdersRequestsRoute
  '/policies': typeof PoliciesRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/salon-management': typeof SalonManagementRoute
  '/venue-booking': typeof VenueBookingRoute
  '/api/bookings-active-count': typeof ApiBookingsActiveCountRoute
  '/api/bookings-recent': typeof ApiBookingsRecentRoute
  '/api/hall-bookings': typeof ApiHallBookingsRoute
  '/api/menu-items': typeof ApiMenuItemsRouteWithChildren
  '/api/new-bookings-count': typeof ApiNewBookingsCountRoute
  '/api/orders-and-requests': typeof ApiOrdersAndRequestsRoute
  '/api/salon-bookings': typeof ApiSalonBookingsRouteWithChildren
  '/api/save-booking': typeof ApiSaveBookingRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/sync-reservations': typeof ApiSyncReservationsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/api/menu-items/$id': typeof ApiMenuItemsIdRoute
  '/api/messages/conversation': typeof ApiMessagesConversationRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/mark-read': typeof ApiMessagesMarkReadRoute
  '/api/messages/message': typeof ApiMessagesMessageRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/pms/migrate': typeof ApiPmsMigrateRoute
  '/api/pms/room-status': typeof ApiPmsRoomStatusRoute
  '/api/pms/shift-cashout': typeof ApiPmsShiftCashoutRoute
  '/api/guest-requests/$id/status': typeof ApiGuestRequestsIdStatusRoute
  '/api/room-orders/$id/status': typeof ApiRoomOrdersIdStatusRoute
  '/api/salon-bookings/$id/status': typeof ApiSalonBookingsIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-admin': typeof HotelAdminRoute
  '/menu-management': typeof MenuManagementRoute
  '/my-bookings': typeof MyBookingsRoute
  '/offers': typeof OffersRoute
  '/orders-requests': typeof OrdersRequestsRoute
  '/policies': typeof PoliciesRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/salon-management': typeof SalonManagementRoute
  '/venue-booking': typeof VenueBookingRoute
  '/api/bookings-active-count': typeof ApiBookingsActiveCountRoute
  '/api/bookings-recent': typeof ApiBookingsRecentRoute
  '/api/hall-bookings': typeof ApiHallBookingsRoute
  '/api/menu-items': typeof ApiMenuItemsRouteWithChildren
  '/api/new-bookings-count': typeof ApiNewBookingsCountRoute
  '/api/orders-and-requests': typeof ApiOrdersAndRequestsRoute
  '/api/salon-bookings': typeof ApiSalonBookingsRouteWithChildren
  '/api/save-booking': typeof ApiSaveBookingRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/sync-reservations': typeof ApiSyncReservationsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/api/menu-items/$id': typeof ApiMenuItemsIdRoute
  '/api/messages/conversation': typeof ApiMessagesConversationRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/mark-read': typeof ApiMessagesMarkReadRoute
  '/api/messages/message': typeof ApiMessagesMessageRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/pms/migrate': typeof ApiPmsMigrateRoute
  '/api/pms/room-status': typeof ApiPmsRoomStatusRoute
  '/api/pms/shift-cashout': typeof ApiPmsShiftCashoutRoute
  '/api/guest-requests/$id/status': typeof ApiGuestRequestsIdStatusRoute
  '/api/room-orders/$id/status': typeof ApiRoomOrdersIdStatusRoute
  '/api/salon-bookings/$id/status': typeof ApiSalonBookingsIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-admin': typeof HotelAdminRoute
  '/menu-management': typeof MenuManagementRoute
  '/my-bookings': typeof MyBookingsRoute
  '/offers': typeof OffersRoute
  '/orders-requests': typeof OrdersRequestsRoute
  '/policies': typeof PoliciesRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/salon-management': typeof SalonManagementRoute
  '/venue-booking': typeof VenueBookingRoute
  '/api/bookings-active-count': typeof ApiBookingsActiveCountRoute
  '/api/bookings-recent': typeof ApiBookingsRecentRoute
  '/api/hall-bookings': typeof ApiHallBookingsRoute
  '/api/menu-items': typeof ApiMenuItemsRouteWithChildren
  '/api/new-bookings-count': typeof ApiNewBookingsCountRoute
  '/api/orders-and-requests': typeof ApiOrdersAndRequestsRoute
  '/api/salon-bookings': typeof ApiSalonBookingsRouteWithChildren
  '/api/save-booking': typeof ApiSaveBookingRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/sync-reservations': typeof ApiSyncReservationsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/api/menu-items/$id': typeof ApiMenuItemsIdRoute
  '/api/messages/conversation': typeof ApiMessagesConversationRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/mark-read': typeof ApiMessagesMarkReadRoute
  '/api/messages/message': typeof ApiMessagesMessageRoute
  '/api/messages/reply': typeof ApiMessagesReplyRoute
  '/api/messages/thread': typeof ApiMessagesThreadRoute
  '/api/pms/migrate': typeof ApiPmsMigrateRoute
  '/api/pms/room-status': typeof ApiPmsRoomStatusRoute
  '/api/pms/shift-cashout': typeof ApiPmsShiftCashoutRoute
  '/api/guest-requests/$id/status': typeof ApiGuestRequestsIdStatusRoute
  '/api/room-orders/$id/status': typeof ApiRoomOrdersIdStatusRoute
  '/api/salon-bookings/$id/status': typeof ApiSalonBookingsIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hotel-admin'
    | '/menu-management'
    | '/my-bookings'
    | '/offers'
    | '/orders-requests'
    | '/policies'
    | '/restaurant'
    | '/rooms'
    | '/salon-management'
    | '/venue-booking'
    | '/api/bookings-active-count'
    | '/api/bookings-recent'
    | '/api/hall-bookings'
    | '/api/menu-items'
    | '/api/new-bookings-count'
    | '/api/orders-and-requests'
    | '/api/salon-bookings'
    | '/api/save-booking'
    | '/api/settings'
    | '/api/sync-reservations'
    | '/rooms/$slug'
    | '/api/menu-items/$id'
    | '/api/messages/conversation'
    | '/api/messages/conversations'
    | '/api/messages/mark-read'
    | '/api/messages/message'
    | '/api/messages/reply'
    | '/api/messages/thread'
    | '/api/pms/migrate'
    | '/api/pms/room-status'
    | '/api/pms/shift-cashout'
    | '/api/guest-requests/$id/status'
    | '/api/room-orders/$id/status'
    | '/api/salon-bookings/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hotel-admin'
    | '/menu-management'
    | '/my-bookings'
    | '/offers'
    | '/orders-requests'
    | '/policies'
    | '/restaurant'
    | '/rooms'
    | '/salon-management'
    | '/venue-booking'
    | '/api/bookings-active-count'
    | '/api/bookings-recent'
    | '/api/hall-bookings'
    | '/api/menu-items'
    | '/api/new-bookings-count'
    | '/api/orders-and-requests'
    | '/api/salon-bookings'
    | '/api/save-booking'
    | '/api/settings'
    | '/api/sync-reservations'
    | '/rooms/$slug'
    | '/api/menu-items/$id'
    | '/api/messages/conversation'
    | '/api/messages/conversations'
    | '/api/messages/mark-read'
    | '/api/messages/message'
    | '/api/messages/reply'
    | '/api/messages/thread'
    | '/api/pms/migrate'
    | '/api/pms/room-status'
    | '/api/pms/shift-cashout'
    | '/api/guest-requests/$id/status'
    | '/api/room-orders/$id/status'
    | '/api/salon-bookings/$id/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hotel-admin'
    | '/menu-management'
    | '/my-bookings'
    | '/offers'
    | '/orders-requests'
    | '/policies'
    | '/restaurant'
    | '/rooms'
    | '/salon-management'
    | '/venue-booking'
    | '/api/bookings-active-count'
    | '/api/bookings-recent'
    | '/api/hall-bookings'
    | '/api/menu-items'
    | '/api/new-bookings-count'
    | '/api/orders-and-requests'
    | '/api/salon-bookings'
    | '/api/save-booking'
    | '/api/settings'
    | '/api/sync-reservations'
    | '/rooms/$slug'
    | '/api/menu-items/$id'
    | '/api/messages/conversation'
    | '/api/messages/conversations'
    | '/api/messages/mark-read'
    | '/api/messages/message'
    | '/api/messages/reply'
    | '/api/messages/thread'
    | '/api/pms/migrate'
    | '/api/pms/room-status'
    | '/api/pms/shift-cashout'
    | '/api/guest-requests/$id/status'
    | '/api/room-orders/$id/status'
    | '/api/salon-bookings/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HotelAdminRoute: typeof HotelAdminRoute
  MenuManagementRoute: typeof MenuManagementRoute
  MyBookingsRoute: typeof MyBookingsRoute
  OffersRoute: typeof OffersRoute
  OrdersRequestsRoute: typeof OrdersRequestsRoute
  PoliciesRoute: typeof PoliciesRoute
  RestaurantRoute: typeof RestaurantRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SalonManagementRoute: typeof SalonManagementRoute
  VenueBookingRoute: typeof VenueBookingRoute
  ApiBookingsActiveCountRoute: typeof ApiBookingsActiveCountRoute
  ApiBookingsRecentRoute: typeof ApiBookingsRecentRoute
  ApiHallBookingsRoute: typeof ApiHallBookingsRoute
  ApiMenuItemsRoute: typeof ApiMenuItemsRouteWithChildren
  ApiNewBookingsCountRoute: typeof ApiNewBookingsCountRoute
  ApiOrdersAndRequestsRoute: typeof ApiOrdersAndRequestsRoute
  ApiSalonBookingsRoute: typeof ApiSalonBookingsRouteWithChildren
  ApiSaveBookingRoute: typeof ApiSaveBookingRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiSyncReservationsRoute: typeof ApiSyncReservationsRoute
  ApiMessagesConversationRoute: typeof ApiMessagesConversationRoute
  ApiMessagesConversationsRoute: typeof ApiMessagesConversationsRoute
  ApiMessagesMarkReadRoute: typeof ApiMessagesMarkReadRoute
  ApiMessagesMessageRoute: typeof ApiMessagesMessageRoute
  ApiMessagesReplyRoute: typeof ApiMessagesReplyRoute
  ApiMessagesThreadRoute: typeof ApiMessagesThreadRoute
  ApiPmsMigrateRoute: typeof ApiPmsMigrateRoute
  ApiPmsRoomStatusRoute: typeof ApiPmsRoomStatusRoute
  ApiPmsShiftCashoutRoute: typeof ApiPmsShiftCashoutRoute
  ApiGuestRequestsIdStatusRoute: typeof ApiGuestRequestsIdStatusRoute
  ApiRoomOrdersIdStatusRoute: typeof ApiRoomOrdersIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue-booking': {
      id: '/venue-booking'
      path: '/venue-booking'
      fullPath: '/venue-booking'
      preLoaderRoute: typeof VenueBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-management': {
      id: '/salon-management'
      path: '/salon-management'
      fullPath: '/salon-management'
      preLoaderRoute: typeof SalonManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders-requests': {
      id: '/orders-requests'
      path: '/orders-requests'
      fullPath: '/orders-requests'
      preLoaderRoute: typeof OrdersRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-management': {
      id: '/menu-management'
      path: '/menu-management'
      fullPath: '/menu-management'
      preLoaderRoute: typeof MenuManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-admin': {
      id: '/hotel-admin'
      path: '/hotel-admin'
      fullPath: '/hotel-admin'
      preLoaderRoute: typeof HotelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/api/sync-reservations': {
      id: '/api/sync-reservations'
      path: '/api/sync-reservations'
      fullPath: '/api/sync-reservations'
      preLoaderRoute: typeof ApiSyncReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-booking': {
      id: '/api/save-booking'
      path: '/api/save-booking'
      fullPath: '/api/save-booking'
      preLoaderRoute: typeof ApiSaveBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salon-bookings': {
      id: '/api/salon-bookings'
      path: '/api/salon-bookings'
      fullPath: '/api/salon-bookings'
      preLoaderRoute: typeof ApiSalonBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders-and-requests': {
      id: '/api/orders-and-requests'
      path: '/api/orders-and-requests'
      fullPath: '/api/orders-and-requests'
      preLoaderRoute: typeof ApiOrdersAndRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/new-bookings-count': {
      id: '/api/new-bookings-count'
      path: '/api/new-bookings-count'
      fullPath: '/api/new-bookings-count'
      preLoaderRoute: typeof ApiNewBookingsCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-items': {
      id: '/api/menu-items'
      path: '/api/menu-items'
      fullPath: '/api/menu-items'
      preLoaderRoute: typeof ApiMenuItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hall-bookings': {
      id: '/api/hall-bookings'
      path: '/api/hall-bookings'
      fullPath: '/api/hall-bookings'
      preLoaderRoute: typeof ApiHallBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings-recent': {
      id: '/api/bookings-recent'
      path: '/api/bookings-recent'
      fullPath: '/api/bookings-recent'
      preLoaderRoute: typeof ApiBookingsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings-active-count': {
      id: '/api/bookings-active-count'
      path: '/api/bookings-active-count'
      fullPath: '/api/bookings-active-count'
      preLoaderRoute: typeof ApiBookingsActiveCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pms/shift-cashout': {
      id: '/api/pms/shift-cashout'
      path: '/api/pms/shift-cashout'
      fullPath: '/api/pms/shift-cashout'
      preLoaderRoute: typeof ApiPmsShiftCashoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pms/room-status': {
      id: '/api/pms/room-status'
      path: '/api/pms/room-status'
      fullPath: '/api/pms/room-status'
      preLoaderRoute: typeof ApiPmsRoomStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pms/migrate': {
      id: '/api/pms/migrate'
      path: '/api/pms/migrate'
      fullPath: '/api/pms/migrate'
      preLoaderRoute: typeof ApiPmsMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/thread': {
      id: '/api/messages/thread'
      path: '/api/messages/thread'
      fullPath: '/api/messages/thread'
      preLoaderRoute: typeof ApiMessagesThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/reply': {
      id: '/api/messages/reply'
      path: '/api/messages/reply'
      fullPath: '/api/messages/reply'
      preLoaderRoute: typeof ApiMessagesReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/message': {
      id: '/api/messages/message'
      path: '/api/messages/message'
      fullPath: '/api/messages/message'
      preLoaderRoute: typeof ApiMessagesMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/mark-read': {
      id: '/api/messages/mark-read'
      path: '/api/messages/mark-read'
      fullPath: '/api/messages/mark-read'
      preLoaderRoute: typeof ApiMessagesMarkReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/conversations': {
      id: '/api/messages/conversations'
      path: '/api/messages/conversations'
      fullPath: '/api/messages/conversations'
      preLoaderRoute: typeof ApiMessagesConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/conversation': {
      id: '/api/messages/conversation'
      path: '/api/messages/conversation'
      fullPath: '/api/messages/conversation'
      preLoaderRoute: typeof ApiMessagesConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-items/$id': {
      id: '/api/menu-items/$id'
      path: '/$id'
      fullPath: '/api/menu-items/$id'
      preLoaderRoute: typeof ApiMenuItemsIdRouteImport
      parentRoute: typeof ApiMenuItemsRoute
    }
    '/api/salon-bookings/$id/status': {
      id: '/api/salon-bookings/$id/status'
      path: '/$id/status'
      fullPath: '/api/salon-bookings/$id/status'
      preLoaderRoute: typeof ApiSalonBookingsIdStatusRouteImport
      parentRoute: typeof ApiSalonBookingsRoute
    }
    '/api/room-orders/$id/status': {
      id: '/api/room-orders/$id/status'
      path: '/api/room-orders/$id/status'
      fullPath: '/api/room-orders/$id/status'
      preLoaderRoute: typeof ApiRoomOrdersIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-requests/$id/status': {
      id: '/api/guest-requests/$id/status'
      path: '/api/guest-requests/$id/status'
      fullPath: '/api/guest-requests/$id/status'
      preLoaderRoute: typeof ApiGuestRequestsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface ApiMenuItemsRouteChildren {
  ApiMenuItemsIdRoute: typeof ApiMenuItemsIdRoute
}

const ApiMenuItemsRouteChildren: ApiMenuItemsRouteChildren = {
  ApiMenuItemsIdRoute: ApiMenuItemsIdRoute,
}

const ApiMenuItemsRouteWithChildren = ApiMenuItemsRoute._addFileChildren(
  ApiMenuItemsRouteChildren,
)

interface ApiSalonBookingsRouteChildren {
  ApiSalonBookingsIdStatusRoute: typeof ApiSalonBookingsIdStatusRoute
}

const ApiSalonBookingsRouteChildren: ApiSalonBookingsRouteChildren = {
  ApiSalonBookingsIdStatusRoute: ApiSalonBookingsIdStatusRoute,
}

const ApiSalonBookingsRouteWithChildren =
  ApiSalonBookingsRoute._addFileChildren(ApiSalonBookingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HotelAdminRoute: HotelAdminRoute,
  MenuManagementRoute: MenuManagementRoute,
  MyBookingsRoute: MyBookingsRoute,
  OffersRoute: OffersRoute,
  OrdersRequestsRoute: OrdersRequestsRoute,
  PoliciesRoute: PoliciesRoute,
  RestaurantRoute: RestaurantRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SalonManagementRoute: SalonManagementRoute,
  VenueBookingRoute: VenueBookingRoute,
  ApiBookingsActiveCountRoute: ApiBookingsActiveCountRoute,
  ApiBookingsRecentRoute: ApiBookingsRecentRoute,
  ApiHallBookingsRoute: ApiHallBookingsRoute,
  ApiMenuItemsRoute: ApiMenuItemsRouteWithChildren,
  ApiNewBookingsCountRoute: ApiNewBookingsCountRoute,
  ApiOrdersAndRequestsRoute: ApiOrdersAndRequestsRoute,
  ApiSalonBookingsRoute: ApiSalonBookingsRouteWithChildren,
  ApiSaveBookingRoute: ApiSaveBookingRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiSyncReservationsRoute: ApiSyncReservationsRoute,
  ApiMessagesConversationRoute: ApiMessagesConversationRoute,
  ApiMessagesConversationsRoute: ApiMessagesConversationsRoute,
  ApiMessagesMarkReadRoute: ApiMessagesMarkReadRoute,
  ApiMessagesMessageRoute: ApiMessagesMessageRoute,
  ApiMessagesReplyRoute: ApiMessagesReplyRoute,
  ApiMessagesThreadRoute: ApiMessagesThreadRoute,
  ApiPmsMigrateRoute: ApiPmsMigrateRoute,
  ApiPmsRoomStatusRoute: ApiPmsRoomStatusRoute,
  ApiPmsShiftCashoutRoute: ApiPmsShiftCashoutRoute,
  ApiGuestRequestsIdStatusRoute: ApiGuestRequestsIdStatusRoute,
  ApiRoomOrdersIdStatusRoute: ApiRoomOrdersIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
